live_config_reload = true

import = ["~/.config/alacritty/themes/dracula.toml"]

[shell]
program = "/opt/homebrew/bin/fish"

[window]
opacity = 0.85
blur = true

[font]
size = 12

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[selection]
save_to_clipboard = false

[cursor]
style.shape = "Block"
